version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile # Learning purpose
    image: webapp:2.0
    ports:
      - "80:8080"
    restart: always
    networks:
      - maarsu-private
networks:
  maarsu-private: